export const ACTIONS = {
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  SET_USER: 'SET_USER',
  REFRESH_QUESTION: 'REFRESH_QUESTION',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  UPDATE_ANSWER: 'UPDATE_ANSWER',
  ADD_QUESTION: 'ADD_QUESTION',
  ADD_ANSWER: 'ADD_ANSWER',
  ADD_COMMENT: 'ADD_COMMENT'
}; 